{
	"name": "PhilipsHue",
	"version": "1.1.11",
	"icon": "far fa-lightbulb",
	"category": "automation",
	"author": "Psychokiller1888",
	"maintainers": [
		"Jierka",
		"maxbachmann",
		"Fe3lApAcUt",
		"MarinDodouss"
	],
	"desc": "Control your Philips Hue lamps",
	"aliceMinVersion": "1.0.0-a5",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"de",
			"fr"
		]
	}
}
